
stages:
  - build

build:bbc_microbit:
  stage: build
  script:
    - mkdir build
    - ./autogen.sh
    - cd build
    - ../configure --with-machine=bbc_microbit --host=arm-none-eabi
    - make
    - arm-none-eabi-objcopy -O binary src/kernel/kernel src/kernel.bin
    - arm-none-eabi-objcopy -O ihex src/kernel/kernel src/kernel.hex
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - build/src/kernel/kernel
      - build/src/kernel.bin
      - build/src/kernel.hex
    expire_in: 1 day

build:beaglexm:
  stage: build
  script:
    - mkdir build
    - ./autogen.sh
    - cd build
    - ../configure --with-machine=beaglexm --host=arm-none-eabi
    - make
    - arm-none-eabi-objcopy -O binary src/kernel/kernel src/kernel.bin
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - build/src/kernel/kernel
      - build/src/kernel.bin
    expire_in: 1 day

build:iGEPv5:
  stage: build
  script:
    - mkdir build
    - ./autogen.sh
    - cd build
    - ../configure --with-machine=iGEPv5 --host=arm-none-eabi
    - make
    - arm-none-eabi-objcopy -O binary src/kernel/kernel src/kernel.bin
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - build/src/kernel/kernel
      - build/src/kernel.bin
    expire_in: 1 day 

build:hosted:
  stage: build
  script:
    - mkdir build
    - ./autogen.sh
    - cd build
    - ../configure --with-machine=hosted
    - make
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - build/src/kernel/kernel
    expire_in: 1 day 

build:i286_pc:
  stage: build
  script:
    - mkdir build
    - ./autogen.sh
    - cd build
    - ../configure --with-machine=i286_pc --host=i386-elf
    - make
