/***************************************************************************
 * Build VSMAv6 sections.
 * See ARM Architecture reference manual, Issue 'I' - July 2005 Chapter B4.
 ***************************************************************************/
#pragma once

typedef unsigned int VMSAv6_section_t;

/* bit 1 is set, and bit 18 is clear on sections. */
#define VMSAv6_SECTION_BITS ((0<<18)|(1<< 1))

/* convert a 32bit physical address into the base address components of a section. */
#define VMSAv6_SECTION_BASEADDR(base32) \
	( base32 & 0xfff00000 )


#define VMSAv6_SECTION_XN(xn1)      ( xn1  <<  4 ) /* EXECUTE NEVER              */
#define VMSAv6_SECTION_S(s1)        ( s1   << 16 ) /* SHARED                     */
#define VMSAv6_SECTION_nG(ng1)      ( ng1  << 17 ) /* NOT GLOBAL                 */
#define VMSAv6_SECTION_AP(ap2)      ( ap2  << 10 ) /* access permission          */
#define VMSAv6_SECTION_APX(apx1)    ( apx1 << 15 ) /* access permission extended */
#define VMSAv6_SECTION_DOMAIN(dom4) ( dom4 <<  5 ) /* DOMAIN                     */
#define VMSAv6_SECTION_B(b1)        ( b1   <<  2 ) /* BUFFER        	          */
#define VMSAv6_SECTION_C(c1)        ( c1   <<  3 ) /* CACHE              	      */
#define VMSAv6_SECTION_TEX(tex3)    ( tex3 << 12 ) /* Type Extension Field       */


/***************************************************************************
 *             ENUMERATED SECTION ACCESS PERMISSIONS
 ***************************************************************************/
typedef enum VMSAv6_section_access_permission {

	/*** Privileged: NONE, User: NONE ***/
	VMSAv6_SECTION_ACCESS_NONE =
			VMSAv6_SECTION_APX(0) | VMSAv6_SECTION_AP(0),

	/*** Privileged: Read/Write, User: NONE ***/
	VMSAv6_SECTION_ACCESS_PRIVILEGED_FULL =
			VMSAv6_SECTION_APX(0) | VMSAv6_SECTION_AP(1),

	/*** Privileged: Read/Write, User: ReadOnly ***/
	VMSAv6_SECTION_ACCESS_PRIVILEGED_FULL_USER_READONLY =
			VMSAv6_SECTION_APX(0) | VMSAv6_SECTION_AP(2),

	/*** Privileged: Read/Write, User: ReadWrite ***/
	VMSAv6_SECTION_ACCESS_FULL =
			VMSAv6_SECTION_APX(0) | VMSAv6_SECTION_AP(3),

	/*** Privileged: ReadOnly, User: NONE ***/
	VMSAv6_SECTION_ACCESS_PRIVILEGED_READONLY =
			VMSAv6_SECTION_APX(1) | VMSAv6_SECTION_AP(1),

	/*** Privileged: ReadOnly, User: ReadOnly ***/
	VMSAv6_SECTION_ACCESS_READONLY =
			VMSAv6_SECTION_APX(1) | VMSAv6_SECTION_AP(2),

} VMSAv6_section_access_permission_enum_t;


/***************************************************************************
 *             ENUMERATED SECTION DOMAINS
 ***************************************************************************/
typedef enum VMSAv6_section_domain {

	VMSAv6_SECTION_DOMAIN_0  = VMSAv6_SECTION_DOMAIN( 0),
	VMSAv6_SECTION_DOMAIN_1  = VMSAv6_SECTION_DOMAIN( 1),
	VMSAv6_SECTION_DOMAIN_2  = VMSAv6_SECTION_DOMAIN( 2),
	VMSAv6_SECTION_DOMAIN_3  = VMSAv6_SECTION_DOMAIN( 3),
	VMSAv6_SECTION_DOMAIN_4  = VMSAv6_SECTION_DOMAIN( 4),
	VMSAv6_SECTION_DOMAIN_5  = VMSAv6_SECTION_DOMAIN( 5),
	VMSAv6_SECTION_DOMAIN_6  = VMSAv6_SECTION_DOMAIN( 6),
	VMSAv6_SECTION_DOMAIN_7  = VMSAv6_SECTION_DOMAIN( 7),
	VMSAv6_SECTION_DOMAIN_8  = VMSAv6_SECTION_DOMAIN( 8),
	VMSAv6_SECTION_DOMAIN_9  = VMSAv6_SECTION_DOMAIN( 9),
	VMSAv6_SECTION_DOMAIN_10 = VMSAv6_SECTION_DOMAIN(10),
	VMSAv6_SECTION_DOMAIN_11 = VMSAv6_SECTION_DOMAIN(11),
	VMSAv6_SECTION_DOMAIN_12 = VMSAv6_SECTION_DOMAIN(12),
	VMSAv6_SECTION_DOMAIN_13 = VMSAv6_SECTION_DOMAIN(13),
	VMSAv6_SECTION_DOMAIN_14 = VMSAv6_SECTION_DOMAIN(14),
	VMSAv6_SECTION_DOMAIN_15 = VMSAv6_SECTION_DOMAIN(15),

} VMSAv6_section_domain_enum_t;

/***************************************************************************
 *             ENUMERATED SECTION MEMORY TYPES
 ***************************************************************************/
typedef enum VMSAv6_SECTION_memtype {

	VMSAv6_SECTION_MEMTYPE_SHARED_STRONGLY_ORDERED =
		VMSAv6_SECTION_TEX(0) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(0),

	VMSAv6_SECTION_MEMTYPE_SHARED_DEVICE =
		VMSAv6_SECTION_TEX(0) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(1),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_WRITETHROUGH =
		VMSAv6_SECTION_TEX(0) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_WRITETHROUGH =
		VMSAv6_SECTION_TEX(0) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_WRITEBACK =
		VMSAv6_SECTION_TEX(0) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_WRITEBACK =
		VMSAv6_SECTION_TEX(0) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_NONCACHEABLE =
		VMSAv6_SECTION_TEX(1) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_NONCACHEABLE =
		VMSAv6_SECTION_TEX(1) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SECTION_TEX(1) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SECTION_TEX(1) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_DEVICE =
		VMSAv6_SECTION_TEX(2) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(0),

 	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_NOCACHEABLE =
		VMSAv6_SECTION_TEX(4) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SECTION_TEX(4) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITETHROUGH =
		VMSAv6_SECTION_TEX(4) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK =
		VMSAv6_SECTION_TEX(4) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_NOCACHEABLE =
		VMSAv6_SECTION_TEX(5) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SECTION_TEX(5) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITETHROUGH =
		VMSAv6_SECTION_TEX(5) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK =
		VMSAv6_SECTION_TEX(5) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_NOCACHEABLE =
		VMSAv6_SECTION_TEX(6) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SECTION_TEX(6) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITETHROUGH =
		VMSAv6_SECTION_TEX(6) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK =
		VMSAv6_SECTION_TEX(6) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_NOCACHEABLE =
		VMSAv6_SECTION_TEX(7) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SECTION_TEX(7) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITETHROUGH =
		VMSAv6_SECTION_TEX(7) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK =
		VMSAv6_SECTION_TEX(7) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(0),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_NOCACHEABLE =
		VMSAv6_SECTION_TEX(4) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SECTION_TEX(4) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITETHROUGH =
		VMSAv6_SECTION_TEX(4) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK =
		VMSAv6_SECTION_TEX(4) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_NOCACHEABLE =
		VMSAv6_SECTION_TEX(5) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SECTION_TEX(5) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITETHROUGH =
		VMSAv6_SECTION_TEX(5) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK =
		VMSAv6_SECTION_TEX(5) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_NOCACHEABLE =
		VMSAv6_SECTION_TEX(6) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SECTION_TEX(6) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITETHROUGH =
		VMSAv6_SECTION_TEX(6) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK =
		VMSAv6_SECTION_TEX(6) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_NOCACHEABLE =
		VMSAv6_SECTION_TEX(7) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SECTION_TEX(7) | VMSAv6_SECTION_C(0) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITETHROUGH =
		VMSAv6_SECTION_TEX(7) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(0) | VMSAv6_SECTION_S(1),

	VMSAv6_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK =
		VMSAv6_SECTION_TEX(7) | VMSAv6_SECTION_C(1) | VMSAv6_SECTION_B(1) | VMSAv6_SECTION_S(1),

}VMSAv6_SECTION_memtype_enum_t;


static inline vmsav6_build_section(
		VMSAv6_section_t *                      s,
		phy_addr32_t                            phy_addr,
		VMSAv6_section_memtype_enum_t           mem_type,
		VMSAv6_section_domain_enum_t            domain,
		VMSAv6_section_access_permission_enum_t access)
{
	*s  = VMSAv6_SECTION_BITS                    |
	      VMSAv6_SECTION_BASEADDR(phy_addr)      |
	      mem_type                               |
	      domain                                 |
	      access                                 ;
}
