
/***************************************************************************
 * Build VSMAv6 super sections.
 * See ARM Architecture reference manual, Issue 'I' - July 2005 Chapter B4.
 ***************************************************************************/
#pragma once

typedef unsigned int VMSAv6_supersection_t;

/* bits 1 and 18 are set on super sections. */
#define VMSAv6_SUPERSECTION_BITS ((1<<18)|(1<< 1))

/* convert a 32bit physical address into the base address components of a super section. */
#define VMSAv6_SUPERSECTION_BASEADDR_32(base32) \
	( base32 & 0x00ff000000 )

/* convert a 40bit physical address into the base address components of a super section. */
#define VMSAv6_SUPERSECTION_BASEADDR_40(base40) \
	( ( base40 & 0x00ff000000ULL ) >>  0 ) | \
	( ( base40 & 0x0f00000000ULL ) >> 12 ) | \
	( ( base40 & 0xf000000000ULL ) >> 31 )

#define VMSAv6_SUPERSECTION_XN(xn1)      ( xn1  <<  4 ) /* EXECUTE NEVER              */
#define VMSAv6_SUPERSECTION_S(s1)        ( s1   << 16 ) /* SHARED                     */
#define VMSAv6_SUPERSECTION_nG(ng1)      ( ng1  << 17 ) /* NOT GLOBAL                 */
#define VMSAv6_SUPERSECTION_AP(ap2)      ( ap2  << 10 ) /* access permission          */
#define VMSAv6_SUPERSECTION_APX(apx1)    ( apx1 << 15 ) /* access permission extended */
#define VMSAv6_SUPERSECTION_DOMAIN(dom4) ( dom4 <<  5 ) /* DOMAIN                     */
#define VMSAv6_SUPERSECTION_B(b1)        ( b1   <<  2 ) /* BUFFER        	          */
#define VMSAv6_SUPERSECTION_C(c1)        ( c1   <<  3 ) /* CACHE              	      */
#define VMSAv6_SUPERSECTION_TEX(tex3)    ( tex3 << 12 ) /* Type Extension Field       */


/***************************************************************************
 *             ENUMERATED SUPER SECTION ACCESS PERMISSIONS
 ***************************************************************************/
typedef enum VMSAv6_supersection_access_permission {

	/*** Privileged: NONE, User: NONE ***/
	VMSAv6_SUPERSECTION_ACCESS_NONE =
			VMSAv6_SUPERSECTION_APX(0) | VMSAv6_SUPERSECTION_AP(0),

	/*** Privileged: Read/Write, User: NONE ***/
	VMSAv6_SUPERSECTION_ACCESS_PRIVILEGED_FULL =
			VMSAv6_SUPERSECTION_APX(0) | VMSAv6_SUPERSECTION_AP(1),

	/*** Privileged: Read/Write, User: ReadOnly ***/
	VMSAv6_SUPERSECTION_ACCESS_PRIVILEGED_FULL_USER_READONLY =
			VMSAv6_SUPERSECTION_APX(0) | VMSAv6_SUPERSECTION_AP(2),

	/*** Privileged: Read/Write, User: ReadWrite ***/
	VMSAv6_SUPERSECTION_ACCESS_FULL =
			VMSAv6_SUPERSECTION_APX(0) | VMSAv6_SUPERSECTION_AP(3),

	/*** Privileged: ReadOnly, User: NONE ***/
	VMSAv6_SUPERSECTION_ACCESS_PRIVILEGED_READONLY =
			VMSAv6_SUPERSECTION_APX(1) | VMSAv6_SUPERSECTION_AP(1),

	/*** Privileged: ReadOnly, User: ReadOnly ***/
	VMSAv6_SUPERSECTION_ACCESS_READONLY =
			VMSAv6_SUPERSECTION_APX(1) | VMSAv6_SUPERSECTION_AP(2),

} VMSAv6_supersection_access_permission_enum_t;


/***************************************************************************
 *             ENUMERATED SUPER SECTION DOMAINS
 ***************************************************************************/
typedef enum VMSAv6_supersection_domain {

	VMSAv6_SUPERSECTION_DOMAIN_0  = VMSAv6_SUPERSECTION_DOMAIN( 0),
	VMSAv6_SUPERSECTION_DOMAIN_1  = VMSAv6_SUPERSECTION_DOMAIN( 1),
	VMSAv6_SUPERSECTION_DOMAIN_2  = VMSAv6_SUPERSECTION_DOMAIN( 2),
	VMSAv6_SUPERSECTION_DOMAIN_3  = VMSAv6_SUPERSECTION_DOMAIN( 3),
	VMSAv6_SUPERSECTION_DOMAIN_4  = VMSAv6_SUPERSECTION_DOMAIN( 4),
	VMSAv6_SUPERSECTION_DOMAIN_5  = VMSAv6_SUPERSECTION_DOMAIN( 5),
	VMSAv6_SUPERSECTION_DOMAIN_6  = VMSAv6_SUPERSECTION_DOMAIN( 6),
	VMSAv6_SUPERSECTION_DOMAIN_7  = VMSAv6_SUPERSECTION_DOMAIN( 7),
	VMSAv6_SUPERSECTION_DOMAIN_8  = VMSAv6_SUPERSECTION_DOMAIN( 8),
	VMSAv6_SUPERSECTION_DOMAIN_9  = VMSAv6_SUPERSECTION_DOMAIN( 9),
	VMSAv6_SUPERSECTION_DOMAIN_10 = VMSAv6_SUPERSECTION_DOMAIN(10),
	VMSAv6_SUPERSECTION_DOMAIN_11 = VMSAv6_SUPERSECTION_DOMAIN(11),
	VMSAv6_SUPERSECTION_DOMAIN_12 = VMSAv6_SUPERSECTION_DOMAIN(12),
	VMSAv6_SUPERSECTION_DOMAIN_13 = VMSAv6_SUPERSECTION_DOMAIN(13),
	VMSAv6_SUPERSECTION_DOMAIN_14 = VMSAv6_SUPERSECTION_DOMAIN(14),
	VMSAv6_SUPERSECTION_DOMAIN_15 = VMSAv6_SUPERSECTION_DOMAIN(15),

} VMSAv6_supersection_domain_enum_t;

/***************************************************************************
 *             ENUMERATED SUPER SECTION MEMORY TYPES
 ***************************************************************************/
typedef enum VMSAv6_supersection_memtype {

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_STRONGLY_ORDERED =
		VMSAv6_SUPERSECTION_TEX(0) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(0),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_DEVICE =
		VMSAv6_SUPERSECTION_TEX(0) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(1),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_WRITETHROUGH =
		VMSAv6_SUPERSECTION_TEX(0) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_WRITETHROUGH =
		VMSAv6_SUPERSECTION_TEX(0) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_WRITEBACK =
		VMSAv6_SUPERSECTION_TEX(0) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_WRITEBACK =
		VMSAv6_SUPERSECTION_TEX(0) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_NONCACHEABLE =
		VMSAv6_SUPERSECTION_TEX(1) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_NONCACHEABLE =
		VMSAv6_SUPERSECTION_TEX(1) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SUPERSECTION_TEX(1) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SUPERSECTION_TEX(1) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_DEVICE =
		VMSAv6_SUPERSECTION_TEX(2) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(0),

 	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_NOCACHEABLE =
		VMSAv6_SUPERSECTION_TEX(4) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SUPERSECTION_TEX(4) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITETHROUGH =
		VMSAv6_SUPERSECTION_TEX(4) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK =
		VMSAv6_SUPERSECTION_TEX(4) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_NOCACHEABLE =
		VMSAv6_SUPERSECTION_TEX(5) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SUPERSECTION_TEX(5) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITETHROUGH =
		VMSAv6_SUPERSECTION_TEX(5) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK =
		VMSAv6_SUPERSECTION_TEX(5) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_NOCACHEABLE =
		VMSAv6_SUPERSECTION_TEX(6) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SUPERSECTION_TEX(6) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITETHROUGH =
		VMSAv6_SUPERSECTION_TEX(6) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK =
		VMSAv6_SUPERSECTION_TEX(6) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_NOCACHEABLE =
		VMSAv6_SUPERSECTION_TEX(7) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SUPERSECTION_TEX(7) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITETHROUGH =
		VMSAv6_SUPERSECTION_TEX(7) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK =
		VMSAv6_SUPERSECTION_TEX(7) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(0),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_NOCACHEABLE =
		VMSAv6_SUPERSECTION_TEX(4) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SUPERSECTION_TEX(4) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITETHROUGH =
		VMSAv6_SUPERSECTION_TEX(4) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK =
		VMSAv6_SUPERSECTION_TEX(4) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_NOCACHEABLE =
		VMSAv6_SUPERSECTION_TEX(5) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SUPERSECTION_TEX(5) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITETHROUGH =
		VMSAv6_SUPERSECTION_TEX(5) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK =
		VMSAv6_SUPERSECTION_TEX(5) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_NOCACHEABLE =
		VMSAv6_SUPERSECTION_TEX(6) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SUPERSECTION_TEX(6) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITETHROUGH =
		VMSAv6_SUPERSECTION_TEX(6) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK =
		VMSAv6_SUPERSECTION_TEX(6) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_NOCACHEABLE =
		VMSAv6_SUPERSECTION_TEX(7) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv6_SUPERSECTION_TEX(7) | VMSAv6_SUPERSECTION_C(0) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITETHROUGH =
		VMSAv6_SUPERSECTION_TEX(7) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(0) | VMSAv6_SUPERSECTION_S(1),

	VMSAv6_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK =
		VMSAv6_SUPERSECTION_TEX(7) | VMSAv6_SUPERSECTION_C(1) | VMSAv6_SUPERSECTION_B(1) | VMSAv6_SUPERSECTION_S(1),

}VMSAv6_supersection_memtype_enum_t;


static inline vmsav6_build_supersection32(
		VMSAv6_supersection_t *                      ss,
		phy_addr32_t                                 phy_addr,
		VMSAv6_supersection_memtype_enum_t           mem_type,
		VMSAv6_supersection_domain_enum_t            domain,
		VMSAv6_supersection_access_permission_enum_t access)
{
	*ss = VMSAv6_SUPERSECTION_BITS                  |
		  VMSAv6_SUPERSECTION_BASEADDR_32(phy_addr) |
		  mem_type                                  |
		  domain                                    |
		  access                                    ;
}

static inline vmsav6_build_supersection40(
		VMSAv6_supersection_t *                      ss,
		phy_addr40_t                                 phy_addr,
		VMSAv6_supersection_memtype_enum_t           mem_type,
		VMSAv6_supersection_domain_enum_t            domain,
		VMSAv6_supersection_access_permission_enum_t access)
{
	*ss = VMSAv6_SUPERSECTION_BITS                  |
		  VMSAv6_SUPERSECTION_BASEADDR_40(phy_addr) |
		  mem_type                                  |
		  domain                                    |
		  access                                    ;
}

