/***************************************************************************
 * Build VMSAv7 small pages.
 * See ARM Architecture Reference Manual
 * 	ARMv7-A and ARMv7-R edition ( Issue C.b )
 * 	Section B3.5
 ***************************************************************************/

#pragma once

typedef unsigned int VMSAv7_smallpage_t;

/* bit 1 is set on small pages. */
#define VMSAv7_SMALLPAGE_BITS (1<< 1)

/* convert a 32bit physical address into the base address components of a large page. */
#define VMSAv7_SMALLPAGE_BASEADDR(base32) \
	( base32 & 0xfffff000 )


#define VMSAv7_SMALLPAGE_XN(xn1)      ( xn1  <<  0 ) /* EXECUTE NEVER              */
#define VMSAv7_SMALLPAGE_S(s1)        ( s1   << 10 ) /* SHARED                     */
#define VMSAv7_SMALLPAGE_nG(ng1)      ( ng1  << 11 ) /* NOT GLOBAL                 */
#define VMSAv7_SMALLPAGE_AP(ap2)      ( ap2  <<  4 ) /* access permission          */
#define VMSAv7_SMALLPAGE_APX(apx1)    ( apx1 <<  9 ) /* access permission extended */
#define VMSAv7_SMALLPAGE_B(b1)        ( b1   <<  2 ) /* BUFFER        	          */
#define VMSAv7_SMALLPAGE_C(c1)        ( c1   <<  3 ) /* CACHE              	      */
#define VMSAv7_SMALLPAGE_TEX(tex3)    ( tex3 <<  6 ) /* Type Extension Field       */


/***************************************************************************
 *             ENUMERATED SMALLPAGE ACCESS PERMISSIONS
 ***************************************************************************/
typedef enum VMSAv7_smallpage_access_permission {

	/*** Privileged: NONE, User: NONE ***/
	VMSAv7_SMALLPAGE_ACCESS_NONE =
			VMSAv7_SMALLPAGE_APX(0) | VMSAv7_SMALLPAGE_AP(0),

	/*** Privileged: Read/Write, User: NONE ***/
	VMSAv7_SMALLPAGE_ACCESS_PRIVILEGED_FULL =
			VMSAv7_SMALLPAGE_APX(0) | VMSAv7_SMALLPAGE_AP(1),

	/*** Privileged: Read/Write, User: ReadOnly ***/
	VMSAv7_SMALLPAGE_ACCESS_PRIVILEGED_FULL_USER_READONLY =
			VMSAv7_SMALLPAGE_APX(0) | VMSAv7_SMALLPAGE_AP(2),

	/*** Privileged: Read/Write, User: ReadWrite ***/
	VMSAv7_SMALLPAGE_ACCESS_FULL =
			VMSAv7_SMALLPAGE_APX(0) | VMSAv7_SMALLPAGE_AP(3),

	/*** Privileged: ReadOnly, User: NONE ***/
	VMSAv7_SMALLPAGE_ACCESS_PRIVILEGED_READONLY =
			VMSAv7_SMALLPAGE_APX(1) | VMSAv7_SMALLPAGE_AP(1),

	/*** Privileged: ReadOnly, User: ReadOnly ***/
	VMSAv7_SMALLPAGE_ACCESS_READONLY =
			VMSAv7_SMALLPAGE_APX(1) | VMSAv7_SMALLPAGE_AP(2),

} VMSAv7_smallpage_access_permission_enum_t;


/***************************************************************************
 *             ENUMERATED SMALLPAGE MEMORY TYPES
 ***************************************************************************/
typedef enum VMSAv7_smallpage_memtype {

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_STRONGLY_ORDERED =
		VMSAv7_SMALLPAGE_TEX(0) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(0),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_DEVICE =
		VMSAv7_SMALLPAGE_TEX(0) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(1),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_WRITETHROUGH =
		VMSAv7_SMALLPAGE_TEX(0) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_WRITETHROUGH =
		VMSAv7_SMALLPAGE_TEX(0) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_WRITEBACK =
		VMSAv7_SMALLPAGE_TEX(0) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_WRITEBACK =
		VMSAv7_SMALLPAGE_TEX(0) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_NONCACHEABLE =
		VMSAv7_SMALLPAGE_TEX(1) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_NONCACHEABLE =
		VMSAv7_SMALLPAGE_TEX(1) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SMALLPAGE_TEX(1) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SMALLPAGE_TEX(1) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_DEVICE =
		VMSAv7_SMALLPAGE_TEX(2) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(0),

 	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_NOCACHEABLE =
		VMSAv7_SMALLPAGE_TEX(4) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SMALLPAGE_TEX(4) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITETHROUGH =
		VMSAv7_SMALLPAGE_TEX(4) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK =
		VMSAv7_SMALLPAGE_TEX(4) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_NOCACHEABLE =
		VMSAv7_SMALLPAGE_TEX(5) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SMALLPAGE_TEX(5) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITETHROUGH =
		VMSAv7_SMALLPAGE_TEX(5) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK =
		VMSAv7_SMALLPAGE_TEX(5) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_NOCACHEABLE =
		VMSAv7_SMALLPAGE_TEX(6) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SMALLPAGE_TEX(6) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITETHROUGH =
		VMSAv7_SMALLPAGE_TEX(6) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK =
		VMSAv7_SMALLPAGE_TEX(6) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_NOCACHEABLE =
		VMSAv7_SMALLPAGE_TEX(7) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SMALLPAGE_TEX(7) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITETHROUGH =
		VMSAv7_SMALLPAGE_TEX(7) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK =
		VMSAv7_SMALLPAGE_TEX(7) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(0),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_NOCACHEABLE =
		VMSAv7_SMALLPAGE_TEX(4) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SMALLPAGE_TEX(4) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITETHROUGH =
		VMSAv7_SMALLPAGE_TEX(4) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK =
		VMSAv7_SMALLPAGE_TEX(4) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_NOCACHEABLE =
		VMSAv7_SMALLPAGE_TEX(5) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SMALLPAGE_TEX(5) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITETHROUGH =
		VMSAv7_SMALLPAGE_TEX(5) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK =
		VMSAv7_SMALLPAGE_TEX(5) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_NOCACHEABLE =
		VMSAv7_SMALLPAGE_TEX(6) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SMALLPAGE_TEX(6) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITETHROUGH =
		VMSAv7_SMALLPAGE_TEX(6) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK =
		VMSAv7_SMALLPAGE_TEX(6) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_NOCACHEABLE =
		VMSAv7_SMALLPAGE_TEX(7) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SMALLPAGE_TEX(7) | VMSAv7_SMALLPAGE_C(0) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITETHROUGH =
		VMSAv7_SMALLPAGE_TEX(7) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(0) | VMSAv7_SMALLPAGE_S(1),

	VMSAv7_SMALLPAGE_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK =
		VMSAv7_SMALLPAGE_TEX(7) | VMSAv7_SMALLPAGE_C(1) | VMSAv7_SMALLPAGE_B(1) | VMSAv7_SMALLPAGE_S(1),

}VMSAv7_smallpage_memtype_enum_t;

/***************************************************************************
 *             ENUMERATED SMALLPAGE GLOBAL FLAGS
 ***************************************************************************/
typedef enum VMSAv7_smallpage_global {

	VMSAv7_SMALLPAGE_GLOBAL    = VMSAv7_SMALLPAGE_nG(0),
	VMSAv7_SMALLPAGE_NOTGLOBAL = VMSAv7_SMALLPAGE_nG(1),

} VMSAv7_smallpage_global_t;

/***************************************************************************
 *             ENUMERATED SMALLPAGE EXECUTE NEVER FLAGS
 ***************************************************************************/
typedef enum VMSAv7_smallpage_execute_never {

	VMSAv7_SMALLPAGE_EXECUTE      = VMSAv7_SMALLPAGE_XN(0),
	VMSAv7_SMALLPAGE_EXECUTENEVER = VMSAv7_SMALLPAGE_XN(1),

} VMSAv7_smallpage_execute_never_t;

static inline void vmsav7_build_smallpage(
		VMSAv7_smallpage_t *                      s,
		phy_addr32_t                              phy_addr,
		VMSAv7_smallpage_memtype_enum_t           mem_type,
		VMSAv7_smallpage_access_permission_enum_t access,
		VMSAv7_smallpage_global_t                 global,
		VMSAv7_smallpage_execute_never_t          execute_never)
{
	*s  = VMSAv7_SMALLPAGE_BITS                  |
	      VMSAv7_SMALLPAGE_BASEADDR(phy_addr)    |
	      mem_type                             	 |
	      access                                 |
          global                                 |
          execute_never                          ;
}

