/***************************************************************************
 * Build VMSAv6 super sections.
 * See ARM Architecture Reference Manual
 * 	ARMv7-A and ARMv7-R edition ( Issue C.b )
 * 	Section B3.5
 ***************************************************************************/
#pragma once

typedef unsigned int VMSAv7_supersection_t;

/* bits 1 and 18 are set on super sections. */
#define VMSAv7_SUPERSECTION_BITS ((1<<18)|(1<< 1))

/* convert a 32bit physical address into the base address components of a super section. */
#define VMSAv7_SUPERSECTION_BASEADDR_32(base32) \
	( base32 & 0x00ff000000 )

/* convert a 40bit physical address into the base address components of a super section. */
#define VMSAv7_SUPERSECTION_BASEADDR_40(base40) \
	( ( base40 & 0x00ff000000ULL ) >>  0 ) | \
	( ( base40 & 0x0f00000000ULL ) >> 12 ) | \
	( ( base40 & 0xf000000000ULL ) >> 31 )

#define VMSAv7_SUPERSECTION_XN(xn1)      ( xn1  <<  4 ) // EXECUTE NEVER
#define VMSAv7_SUPERSECTION_S(s1)        ( s1   << 16 ) // SHARED
#define VMSAv7_SUPERSECTION_nG(ng1)      ( ng1  << 17 ) // NOT GLOBAL
#define VMSAv7_SUPERSECTION_AP(ap2)      ( ap2  << 10 ) // access permission
#define VMSAv7_SUPERSECTION_APX(apx1)    ( apx1 << 15 ) // access permission extended
#define VMSAv7_SUPERSECTION_B(b1)        ( b1   <<  2 ) // BUFFER
#define VMSAv7_SUPERSECTION_C(c1)        ( c1   <<  3 ) // CACHE
#define VMSAv7_SUPERSECTION_TEX(tex3)    ( tex3 << 12 ) // Type Extension Field
#define VMSAv7_SUPERSECTION_NS(ns1)    	 ( ns1  << 19 ) // Non-secure ( when accessed from secure state.
#define VMSAv7_SUPERSECTION_PXN(pxn1)	 ( pxn1 <<  0 ) // Privileged execute never

/***************************************************************************
 *             ENUMERATED SUPER SECTION ACCESS PERMISSIONS
 ***************************************************************************/
typedef enum VMSAv7_supersection_access_permission {

	/*** Privileged: NONE, User: NONE ***/
	VMSAv7_SUPERSECTION_ACCESS_NONE =
			VMSAv7_SUPERSECTION_APX(0) | VMSAv7_SUPERSECTION_AP(0),

	/*** Privileged: Read/Write, User: NONE ***/
	VMSAv7_SUPERSECTION_ACCESS_PRIVILEGED_FULL =
			VMSAv7_SUPERSECTION_APX(0) | VMSAv7_SUPERSECTION_AP(1),

	/*** Privileged: Read/Write, User: ReadOnly ***/
	VMSAv7_SUPERSECTION_ACCESS_PRIVILEGED_FULL_USER_READONLY =
			VMSAv7_SUPERSECTION_APX(0) | VMSAv7_SUPERSECTION_AP(2),

	/*** Privileged: Read/Write, User: ReadWrite ***/
	VMSAv7_SUPERSECTION_ACCESS_FULL =
			VMSAv7_SUPERSECTION_APX(0) | VMSAv7_SUPERSECTION_AP(3),

	/*** Privileged: ReadOnly, User: NONE ***/
	VMSAv7_SUPERSECTION_ACCESS_PRIVILEGED_READONLY =
			VMSAv7_SUPERSECTION_APX(1) | VMSAv7_SUPERSECTION_AP(1),

	/*** Privileged: ReadOnly, User: ReadOnly ***/
	VMSAv7_SUPERSECTION_ACCESS_READONLY =
			VMSAv7_SUPERSECTION_APX(1) | VMSAv7_SUPERSECTION_AP(2),

} VMSAv7_supersection_access_permission_enum_t;


/***************************************************************************
 *             ENUMERATED SUPER SECTION MEMORY TYPES
 ***************************************************************************/
typedef enum VMSAv7_supersection_memtype {

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_STRONGLY_ORDERED =
		VMSAv7_SUPERSECTION_TEX(0) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(0),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_DEVICE =
		VMSAv7_SUPERSECTION_TEX(0) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(1),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_WRITETHROUGH =
		VMSAv7_SUPERSECTION_TEX(0) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_WRITETHROUGH =
		VMSAv7_SUPERSECTION_TEX(0) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_WRITEBACK =
		VMSAv7_SUPERSECTION_TEX(0) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_WRITEBACK =
		VMSAv7_SUPERSECTION_TEX(0) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_NONCACHEABLE =
		VMSAv7_SUPERSECTION_TEX(1) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_NONCACHEABLE =
		VMSAv7_SUPERSECTION_TEX(1) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SUPERSECTION_TEX(1) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SUPERSECTION_TEX(1) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_DEVICE =
		VMSAv7_SUPERSECTION_TEX(2) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(0),

 	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_NOCACHEABLE =
		VMSAv7_SUPERSECTION_TEX(4) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SUPERSECTION_TEX(4) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITETHROUGH =
		VMSAv7_SUPERSECTION_TEX(4) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK =
		VMSAv7_SUPERSECTION_TEX(4) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_NOCACHEABLE =
		VMSAv7_SUPERSECTION_TEX(5) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SUPERSECTION_TEX(5) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITETHROUGH =
		VMSAv7_SUPERSECTION_TEX(5) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK =
		VMSAv7_SUPERSECTION_TEX(5) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_NOCACHEABLE =
		VMSAv7_SUPERSECTION_TEX(6) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SUPERSECTION_TEX(6) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITETHROUGH =
		VMSAv7_SUPERSECTION_TEX(6) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK =
		VMSAv7_SUPERSECTION_TEX(6) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_NOCACHEABLE =
		VMSAv7_SUPERSECTION_TEX(7) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SUPERSECTION_TEX(7) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITETHROUGH =
		VMSAv7_SUPERSECTION_TEX(7) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK =
		VMSAv7_SUPERSECTION_TEX(7) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(0),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_NOCACHEABLE =
		VMSAv7_SUPERSECTION_TEX(4) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SUPERSECTION_TEX(4) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITETHROUGH =
		VMSAv7_SUPERSECTION_TEX(4) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK =
		VMSAv7_SUPERSECTION_TEX(4) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_NOCACHEABLE =
		VMSAv7_SUPERSECTION_TEX(5) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SUPERSECTION_TEX(5) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITETHROUGH =
		VMSAv7_SUPERSECTION_TEX(5) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK =
		VMSAv7_SUPERSECTION_TEX(5) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_NOCACHEABLE =
		VMSAv7_SUPERSECTION_TEX(6) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SUPERSECTION_TEX(6) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITETHROUGH =
		VMSAv7_SUPERSECTION_TEX(6) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK =
		VMSAv7_SUPERSECTION_TEX(6) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_NOCACHEABLE =
		VMSAv7_SUPERSECTION_TEX(7) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SUPERSECTION_TEX(7) | VMSAv7_SUPERSECTION_C(0) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITETHROUGH =
		VMSAv7_SUPERSECTION_TEX(7) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(0) | VMSAv7_SUPERSECTION_S(1),

	VMSAv7_SUPERSECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK =
		VMSAv7_SUPERSECTION_TEX(7) | VMSAv7_SUPERSECTION_C(1) | VMSAv7_SUPERSECTION_B(1) | VMSAv7_SUPERSECTION_S(1),

}VMSAv7_supersection_memtype_enum_t;

/***************************************************************************
 *             ENUMERATED SUPER SECTION GLOBAL FLAGS
 ***************************************************************************/
typedef enum VMSAv6_supersection_global {

	VMSAv7_SUPERSECTION_GLOBAL    = VMSAv7_SUPERSECTION_nG(0),
	VMSAv7_SUPERSECTION_NOTGLOBAL = VMSAv7_SUPERSECTION_nG(1),

} VMSAv7_supersection_global_t;

/***************************************************************************
 *             ENUMERATED SUPER SECTION EXECUTE NEVER FLAGS
 ***************************************************************************/
typedef enum VMSAv7_supersection_execute_never {

	VMSAv7_SUPERSECTION_EXECUTE      = VMSAv7_SUPERSECTION_XN(0),
	VMSAv7_SUPERSECTION_EXECUTENEVER = VMSAv7_SUPERSECTION_XN(1),

} VMSAv7_supersection_execute_never_t;

/***************************************************************************
 *         ENUMERATED SUPER SECTION PRIVILEGED EXECUTE NEVER FLAGS
 ***************************************************************************/
typedef enum VMSAv7_supersection_privileged_execute_never {

	VMSAv7_SUPERSECTION_PRIVILEGED_EXECUTE      = VMSAv7_SUPERSECTION_PXN(0),
	VMSAv7_SUPERSECTION_PRIVILEGED_EXECUTENEVER = VMSAv7_SUPERSECTION_PXN(1),

} VMSAv7_supersection_privileged_execute_never_t;

/***************************************************************************
 *         ENUMERATED SUPER SECTION PRIVILEGED EXECUTE NEVER FLAGS
 ***************************************************************************/
typedef enum VMSAv7_supersection_non_secure {

	VMSAv7_SUPERSECTION_SECURE      = VMSAv7_SUPERSECTION_NS(0),
	VMSAv7_SUPERSECTION_NON_SECURE  = VMSAv7_SUPERSECTION_NS(1),

} VMSAv7_supersection_non_secure_t;


static inline void vmsav7_build_supersection32(
		VMSAv7_supersection_t *                      	ss,
		phy_addr32_t                                 	phy_addr,
		VMSAv7_supersection_memtype_enum_t           	mem_type,
		VMSAv7_supersection_access_permission_enum_t 	access,
		VMSAv7_supersection_global_t                 	global,
		VMSAv7_supersection_execute_never_t          	execute_never,
		VMSAv7_supersection_privileged_execute_never_t	privileged_execute_never,
		VMSAv7_supersection_non_secure_t				non_secure)
{
	*ss = VMSAv7_SUPERSECTION_BITS                  |
		  VMSAv7_SUPERSECTION_BASEADDR_32(phy_addr) |
		  mem_type                                  |
		  access                                    |
		  global                                    |
          execute_never                             |
          privileged_execute_never					|
          non_secure								;
}

static inline void vmsav7_build_supersection40(
		VMSAv7_supersection_t *                      	ss,
		phy_addr40_t                                 	phy_addr,
		VMSAv7_supersection_memtype_enum_t           	mem_type,
		VMSAv7_supersection_access_permission_enum_t 	access,
		VMSAv7_supersection_global_t                 	global,
		VMSAv7_supersection_execute_never_t          	execute_never,
		VMSAv7_supersection_privileged_execute_never_t	privileged_execute_never,
		VMSAv7_supersection_non_secure_t				non_secure)
{
	*ss = VMSAv7_SUPERSECTION_BITS                  |
		  VMSAv7_SUPERSECTION_BASEADDR_40(phy_addr) |
		  mem_type                                  |
		  access                                    |
		  global                                    |
          execute_never                             |
          privileged_execute_never					|
          non_secure								;
}

