/***************************************************************************
 * Build VMSAv7 sections.
 * See ARM Architecture Reference Manual
 * 	ARMv7-A and ARMv7-R edition ( Issue C.b )
 * 	Section B3.5
 ***************************************************************************/
#pragma once

typedef unsigned int VMSAv7_section_t;

/* bit 1 is set, and bit 18 is clear on sections. */
#define VMSAv7_SECTION_BITS ((0<<18)|(1<< 1))

/* convert a 32bit physical address into the base address components of a section. */
#define VMSAv7_SECTION_BASEADDR(base32) \
	( base32 & 0xfff00000 )


#define VMSAv7_SECTION_XN(xn1)      	( xn1  <<  4 ) /* EXECUTE NEVER              */
#define VMSAv7_SECTION_S(s1)        	( s1   << 16 ) /* SHARED                     */
#define VMSAv7_SECTION_nG(ng1)      	( ng1  << 17 ) /* NOT GLOBAL                 */
#define VMSAv7_SECTION_AP(ap2)      	( ap2  << 10 ) /* access permission          */
#define VMSAv7_SECTION_APX(apx1)    	( apx1 << 15 ) /* access permission extended */
#define VMSAv7_SECTION_DOMAIN(dom4) 	( dom4 <<  5 ) /* DOMAIN                     */
#define VMSAv7_SECTION_B(b1)        	( b1   <<  2 ) /* BUFFER        	          */
#define VMSAv7_SECTION_C(c1)       		( c1   <<  3 ) /* CACHE              	      */
#define VMSAv7_SECTION_TEX(tex3)		( tex3 << 12 ) /* Type Extension Field       */
#define VMSAv7_SECTION_NS(ns1)    		( ns1  << 19 ) // Non-secure ( when accessed from secure state.
#define VMSAv7_SECTION_PXN(pxn1)		( pxn1 <<  0 ) // Privileged execute never

/***************************************************************************
 *             ENUMERATED SECTION ACCESS PERMISSIONS
 ***************************************************************************/
typedef enum VMSAv7_section_access_permission {

	/*** Privileged: NONE, User: NONE ***/
	VMSAv7_SECTION_ACCESS_NONE =
			VMSAv7_SECTION_APX(0) | VMSAv7_SECTION_AP(0),

	/*** Privileged: Read/Write, User: NONE ***/
	VMSAv7_SECTION_ACCESS_PRIVILEGED_FULL =
			VMSAv7_SECTION_APX(0) | VMSAv7_SECTION_AP(1),

	/*** Privileged: Read/Write, User: ReadOnly ***/
	VMSAv7_SECTION_ACCESS_PRIVILEGED_FULL_USER_READONLY =
			VMSAv7_SECTION_APX(0) | VMSAv7_SECTION_AP(2),

	/*** Privileged: Read/Write, User: ReadWrite ***/
	VMSAv7_SECTION_ACCESS_FULL =
			VMSAv7_SECTION_APX(0) | VMSAv7_SECTION_AP(3),

	/*** Privileged: ReadOnly, User: NONE ***/
	VMSAv7_SECTION_ACCESS_PRIVILEGED_READONLY =
			VMSAv7_SECTION_APX(1) | VMSAv7_SECTION_AP(1),

	/*** Privileged: ReadOnly, User: ReadOnly ***/
	VMSAv7_SECTION_ACCESS_READONLY =
			VMSAv7_SECTION_APX(1) | VMSAv7_SECTION_AP(2),

} VMSAv7_section_access_permission_enum_t;


/***************************************************************************
 *             ENUMERATED SECTION DOMAINS
 ***************************************************************************/
typedef enum VMSAv7_section_domain {

	VMSAv7_SECTION_DOMAIN_0  = VMSAv7_SECTION_DOMAIN( 0),
	VMSAv7_SECTION_DOMAIN_1  = VMSAv7_SECTION_DOMAIN( 1),
	VMSAv7_SECTION_DOMAIN_2  = VMSAv7_SECTION_DOMAIN( 2),
	VMSAv7_SECTION_DOMAIN_3  = VMSAv7_SECTION_DOMAIN( 3),
	VMSAv7_SECTION_DOMAIN_4  = VMSAv7_SECTION_DOMAIN( 4),
	VMSAv7_SECTION_DOMAIN_5  = VMSAv7_SECTION_DOMAIN( 5),
	VMSAv7_SECTION_DOMAIN_6  = VMSAv7_SECTION_DOMAIN( 6),
	VMSAv7_SECTION_DOMAIN_7  = VMSAv7_SECTION_DOMAIN( 7),
	VMSAv7_SECTION_DOMAIN_8  = VMSAv7_SECTION_DOMAIN( 8),
	VMSAv7_SECTION_DOMAIN_9  = VMSAv7_SECTION_DOMAIN( 9),
	VMSAv7_SECTION_DOMAIN_10 = VMSAv7_SECTION_DOMAIN(10),
	VMSAv7_SECTION_DOMAIN_11 = VMSAv7_SECTION_DOMAIN(11),
	VMSAv7_SECTION_DOMAIN_12 = VMSAv7_SECTION_DOMAIN(12),
	VMSAv7_SECTION_DOMAIN_13 = VMSAv7_SECTION_DOMAIN(13),
	VMSAv7_SECTION_DOMAIN_14 = VMSAv7_SECTION_DOMAIN(14),
	VMSAv7_SECTION_DOMAIN_15 = VMSAv7_SECTION_DOMAIN(15),

} VMSAv7_section_domain_enum_t;

/***************************************************************************
 *             ENUMERATED SECTION MEMORY TYPES
 ***************************************************************************/
typedef enum VMSAv7_section_memtype {

	VMSAv7_SECTION_MEMTYPE_SHARED_STRONGLY_ORDERED =
		VMSAv7_SECTION_TEX(0) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(0),

	VMSAv7_SECTION_MEMTYPE_SHARED_DEVICE =
		VMSAv7_SECTION_TEX(0) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(1),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_WRITETHROUGH =
		VMSAv7_SECTION_TEX(0) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_WRITETHROUGH =
		VMSAv7_SECTION_TEX(0) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_WRITEBACK =
		VMSAv7_SECTION_TEX(0) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_WRITEBACK =
		VMSAv7_SECTION_TEX(0) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_NONCACHEABLE =
		VMSAv7_SECTION_TEX(1) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_NONCACHEABLE =
		VMSAv7_SECTION_TEX(1) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SECTION_TEX(1) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SECTION_TEX(1) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_DEVICE =
		VMSAv7_SECTION_TEX(2) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(0),

 	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_NOCACHEABLE =
		VMSAv7_SECTION_TEX(4) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SECTION_TEX(4) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITETHROUGH =
		VMSAv7_SECTION_TEX(4) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK =
		VMSAv7_SECTION_TEX(4) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_NOCACHEABLE =
		VMSAv7_SECTION_TEX(5) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SECTION_TEX(5) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITETHROUGH =
		VMSAv7_SECTION_TEX(5) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK =
		VMSAv7_SECTION_TEX(5) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_NOCACHEABLE =
		VMSAv7_SECTION_TEX(6) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SECTION_TEX(6) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITETHROUGH =
		VMSAv7_SECTION_TEX(6) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK =
		VMSAv7_SECTION_TEX(6) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_NOCACHEABLE =
		VMSAv7_SECTION_TEX(7) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SECTION_TEX(7) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITETHROUGH =
		VMSAv7_SECTION_TEX(7) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_NONSHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK =
		VMSAv7_SECTION_TEX(7) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(0),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_NOCACHEABLE =
		VMSAv7_SECTION_TEX(4) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SECTION_TEX(4) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITETHROUGH =
		VMSAv7_SECTION_TEX(4) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_NOCACHEABLE_INNER_WRITEBACK =
		VMSAv7_SECTION_TEX(4) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_NOCACHEABLE =
		VMSAv7_SECTION_TEX(5) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SECTION_TEX(5) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITETHROUGH =
		VMSAv7_SECTION_TEX(5) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_WRITEALLOCATE_INNER_WRITEBACK =
		VMSAv7_SECTION_TEX(5) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_NOCACHEABLE =
		VMSAv7_SECTION_TEX(6) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SECTION_TEX(6) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITETHROUGH =
		VMSAv7_SECTION_TEX(6) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITETHROUGH_INNER_WRITEBACK =
		VMSAv7_SECTION_TEX(6) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_NOCACHEABLE =
		VMSAv7_SECTION_TEX(7) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK_WRITEALLOCATE =
		VMSAv7_SECTION_TEX(7) | VMSAv7_SECTION_C(0) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITETHROUGH =
		VMSAv7_SECTION_TEX(7) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(0) | VMSAv7_SECTION_S(1),

	VMSAv7_SECTION_MEMTYPE_SHARED_NORMAL_OUTER_WRITEBACK_INNER_WRITEBACK =
		VMSAv7_SECTION_TEX(7) | VMSAv7_SECTION_C(1) | VMSAv7_SECTION_B(1) | VMSAv7_SECTION_S(1),

}VMSAv7_section_memtype_enum_t;

/***************************************************************************
 *             ENUMERATED SECTION GLOBAL FLAGS
 ***************************************************************************/
typedef enum VMSAv7_section_global {

	VMSAv7_SECTION_GLOBAL    = VMSAv7_SECTION_nG(0),
	VMSAv7_SECTION_NOTGLOBAL = VMSAv7_SECTION_nG(1),

} VMSAv7_section_global_t;

/***************************************************************************
 *             ENUMERATED SECTION EXECUTE NEVER FLAGS
 ***************************************************************************/
typedef enum VMSAv7_section_execute_never {

	VMSAv7_SECTION_EXECUTE      = VMSAv7_SECTION_XN(0),
	VMSAv7_SECTION_EXECUTENEVER = VMSAv7_SECTION_XN(1),

} VMSAv7_section_execute_never_t;

/***************************************************************************
 *         ENUMERATED SECTION PRIVILEGED EXECUTE NEVER FLAGS
 ***************************************************************************/
typedef enum VMSAv7_section_privileged_execute_never {

	VMSAv7_SECTION_PRIVILEGED_EXECUTE      = VMSAv7_SECTION_PXN(0),
	VMSAv7_SECTION_PRIVILEGED_EXECUTENEVER = VMSAv7_SECTION_PXN(1),

} VMSAv7_section_privileged_execute_never_t;

/***************************************************************************
 *         ENUMERATED SECTION PRIVILEGED EXECUTE NEVER FLAGS
 ***************************************************************************/
typedef enum VMSAv7_section_non_secure {

	VMSAv7_SECTION_SECURE      = VMSAv7_SECTION_NS(0),
	VMSAv7_SECTION_NON_SECURE  = VMSAv7_SECTION_NS(1),

} VMSAv7_section_non_secure_t;

static inline void vmsav7_build_section(
		VMSAv7_section_t *                      	s,
		phy_addr32_t                            	phy_addr,
		VMSAv7_section_memtype_enum_t           	mem_type,
		VMSAv7_section_domain_enum_t            	domain,
		VMSAv7_section_access_permission_enum_t 	access,
		VMSAv7_section_global_t                 	global,
		VMSAv7_section_execute_never_t          	execute_never,
		VMSAv7_section_privileged_execute_never_t	privileged_execute_never,
		VMSAv7_section_non_secure_t					non_secure)
{
	*s  = VMSAv7_SECTION_BITS                    |
	      VMSAv7_SECTION_BASEADDR(phy_addr)      |
	      mem_type                               |
	      domain                                 |
	      access                                 |
          global                                 |
          execute_never                          |
          privileged_execute_never				 |
          non_secure							 ;
}
