
#pragma once

#define IPSR_EXCEPTION_NUMBER (0x3f)

_ARM_DEFINE_SPECIAL_REG(apsr);
_ARM_DEFINE_SPECIAL_REG(ipsr);
_ARM_DEFINE_SPECIAL_REG(epsr);
_ARM_DEFINE_SPECIAL_REG(iapsr);
_ARM_DEFINE_SPECIAL_REG(eapsr);
_ARM_DEFINE_SPECIAL_REG(xpsr);
_ARM_DEFINE_SPECIAL_REG(iepsr);
