ENTRY(_start)

SECTIONS
{
	. = 0x80200000;
	
	PROVIDE_HIDDEN (__KERNEL_BEGIN = .);

	.text : AT(0x80200000)
	{
		*(.start_text);
			
        *(.text);
	}
	

	.rodata     :
  	{
    	PROVIDE_HIDDEN (__REGISTER_DRIVERS_BEGIN = .);
    	KEEP (*(.register_drivers))
    	PROVIDE_HIDDEN (__REGISTER_DRIVERS_END = .);
    	
    	*(.rodata)
  	}
	

	.data :
	{
		*(.data)
	}
	
	.bss :
	{
		*(.bss)
	}
	
	PROVIDE_HIDDEN (__KERNEL_END = .);
}


